# -*- coding: utf-8 -*-
"""18101143_NigarSulatanaNuha_Assign04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_1a_oMcj69JpBCqmxxIkhEcuTVv_JW3
"""

pip install mglearn

import numpy as np
import pandas as pd

#dataset reading
given_dataset = pd.read_csv('/content/breast cancer classification dataset.csv')

#handling missing values
 given_dataset = given_dataset.dropna(how = 'any', axis = 0)

print(given_dataset.keys())

#encoded categorical features
import sklearn
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
given_dataset['diagnosis'] = enc.fit_transform(given_dataset['diagnosis'])
print(given_dataset[['diagnosis']].head())

#scaling from 0 to 1 using proper scaling technique, min max scaler
import mglearn
mglearn.plots.plot_scaling()

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

cancer= load_breast_cancer()
X_train, X_test, Y_train, Y_test= train_test_split(cancer.data, cancer.target, random_state= 1)

from sklearn.preprocessing import MinMaxScaler
Scaler= MinMaxScaler()
Scaler.fit(X_train)
X_train_scaled= Scaler.transform(X_train)
X_train_scaled= Scaler.transform(X_test)

#features and labels split
features = dataset[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']] 

label = dataset[['diagnosis']]
stratified = pd.DataFrame(label)
cancer= load_breast_cancer()
X_train, X_test, Y_train, Y_test= train_test_split(cancer.data, cancer.target, random_state= 1)

#predicting labels
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, Y_train)
my_prediction = knn.predict(X_test)
print("Test set predictions:\n", my_prediction)
np.mean(knn.score(X_test, Y_test))