# -*- coding: utf-8 -*-
"""18101143_NigarSulatanaNuha_Assign02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TsKLn5XOntfcfgthG0Q3vpgVoOPf9nHm
"""

import numpy as np

#fitness function
def fitness(chromosome):
    horizontal_attackss = sum([chromosome.count(queen)-1 for queen in chromosome])/2
    diagonal_attacks = 0

    n = len(chromosome)
    left_diagonal = [0] * 2*n
    right_diagonal = [0] * 2*n
    for i in range(n):
        left_diagonal[i + chromosome[i] - 1] += 1
        right_diagonal[len(chromosome) - i + chromosome[i] - 2] += 1

    diagonal_attacks= 0
    for i in range(2*n-1):
        count = 0
        if left_diagonal[i] > 1:
            count += left_diagonal[i]-1
        if right_diagonal[i] > 1:
            count += right_diagonal[i]-1
        diagonal_attacks += count / (n- abs(i- n+1))
     
    fitness_score= int(max_fitness - (horizontal_attacks + diagonal_attacks))
    return fitness_score

#Crossover function
def crossover(x, y):
  n= len(x)
  m= random.randint(0, n-1)
  child_chromosome= x[0: m] + y[m: n]

  return child_chromosome

#mutation function
def mutate(child):
  n= len(child)
  m= random.randint(0, n-1)
  p= random.randint(1, n)

  child[m]= p
  
  return child   #mutated_child

def mix_up(chromosome, fitness):
  mixture= fitness(chromosome)/ max_fitness
 
  return mixture

#population with reandomly genarated boards
#random generation of two members
#random generating index numbers
def GA(population, mixtures):
  mixed_population= zip(population, mixtures)
  summation= sum(i for k, i in mixed_population)
  r= random.uniform(0, summation)
  ends= 0
  for k, i in zip(population, mixtures):
    if ends + k >= r:
       return i
    ends += k
  assert False, 'not possible!'

  num_queens= int(input("Please enter the number of Queens: "))

  max_fitness = (num_queens* (num_queens- 1))/ 2

  population= [[random.randint(1, num_queens) for p in range(num_queens)] for p in range(100)]

  while not max_fitness in [fitness(ch) for ch in population]:
     muatation_threshold = 0.03
     new_population= []
     probabilities= [probabilty(n, fitness) for n in population]
    
    
  for i in range(len(population)):
       x= GA(popualtion, mixtures)
       y= GA(population, mixtures)
       child= crossover(x, y)         #crossover function call

       if random.random() < mutation_threshold:
         child= muation(child)

         new_population.append(child)
       if fitness(child) == max_fitness:
         break
      
  population= new_population

  chromosome_output= []
  print('Solved in Generation {}!'.format(generation - 1))

  for ch in population:
    if fitness(ch) == max_fitness:
        chromosome_output= ch

  board= []

  for i in range(num_queens):
     board.append(["X"] * num_queens)

  for n in range(num_queens):
     board[num_queens-chromosome_output[n][n] == "Q"]

  def print_board(board):
     for row in board: 
       print(" ". join(row))

  print_board(board)