# -*- coding: utf-8 -*-
"""alphabeta_pruning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0QO2wpSBJpZl52VoC4YHPC6zHAUSR9c
"""

import numpy as np
import random

def minimax(position, depth, alpha, beta, maximizing_player):
  if (depth == 0):
    return 
  
  
  if maximizing_player:
    maxEval= int(-100000)
    for i in range(int(start_range), int(ending_range)):
      eval = int(minimax(i, depth- 1, alpha, beta, False))
      maxEval= max(maxEval, eval)
      alpha= max(alpha, eval)
      if (beta <= alpha):
        break
    return maxEval
  else:
    minEval= int(100000) 
    for i in range(int(start_range), int(ending_range)):
      eval = int(minimax(i, depth- 1, alpha, beta, True))
      minEval= min(minEval, eval)
      beta= min(beta, eval)
      if (beta <= alpha):
        break
    return minEval

file = open("input_text.txt", 'r')  
data = file.read()  
file.close()  
lines = data.splitlines() 

no_of_turns = lines[0]
no_of_notes = lines[1]

start_range = lines[2].split()[0]
ending_range = lines[2].split()[1]

depth = int(no_of_turns) * 2;
leaf_nodes= int(no_of_notes) ** depth

#head = Node("max", float("-inf"))
#make_tree(depth, head)

#alpha_beta_pruning(head)
#print(head.value)

print(minimax(0, depth, 100000, -100000, True))

print("Depth: " + str(depth))
print("Branch: " + no_of_notes)
print("Terminal States (Leaf Nodes): " + str(leaf_nodes))
print("Maximum amount: ")
print("Comparisons: ")
print("Comparisons: ")

#Maximum amount: 3 maximum amount collected by Riyad
#Comparisons: 9 (before alpha beta pruning)
#Comparisons: 7 (after alpha beta pruning)