# -*- coding: utf-8 -*-
"""18101143_NigarSulatanaNuha_Assign06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Isx6t-WF1KgSUEJBeayvbZFP-pNVWX42
"""

pip install mglearn

import numpy as np
import pandas as pd

#dataset reading
given_dataset = pd.read_csv('/content/breast cancer classification dataset.csv')

#handling missing values
 given_dataset = given_dataset.dropna(how = 'any', axis = 0)

#encoded categorical features
import sklearn
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
given_dataset['diagnosis'] = enc.fit_transform(given_dataset['diagnosis'])
print(given_dataset[['diagnosis']].head())

import mglearn
mglearn.plots.plot_scaling()

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
#splitting dataset
cancer= load_breast_cancer()
X_train, X_test, Y_train, Y_test= train_test_split(cancer.data, cancer.target, random_state= 1)

from sklearn.preprocessing import MinMaxScaler
Scaler= MinMaxScaler()
Scaler.fit(X_train)
X_train_scaled= Scaler.transform(X_train)
X_train_scaled= Scaler.transform(X_test)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=6000)
model.fit(X_train, Y_train)
my_prediction1 = model.predict(X_test)
accuracy_test1 = accuracy_score(Y_test, my_prediction1)
print(accuracy_test1)

#Accuracy calculatiobn using decision tree
from sklearn.tree import DecisionTreeClassifier
clf0 = DecisionTreeClassifier(criterion='entropy',random_state=1)
clf0.fit(X_train,Y_train)
my_prediction2 = clf0.predict(X_test)
accuracy_test2 = accuracy_score(my_prediction2,Y_test)
print(accuracy_test2)

#SVC
from sklearn import svm
clf1= svm.SVC()
clf1.fit(X_train,Y_train)
my_prediction3 = clf1.predict(X_test)
accuracy_test3 = accuracy_score(my_prediction3,Y_test)
print(accuracy_test3)

#MLP classifier
from sklearn.neural_network import MLPClassifier
clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf2.fit(X_train,Y_train)
my_prediction4 = clf2.predict(X_test)
accuracy_test4 = accuracy_score(my_prediction4,Y_test)
print(accuracy_test4)

#Random forest classifier
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=13)
clf3.fit(X_train,Y_train)
my_prediction5 = clf3.predict(X_test)
accuracy_test5 = accuracy_score(my_prediction5,Y_test)
print(accuracy_test5)

#PCA to half
cancer_data=load_breast_cancer()
cancer_data.keys()
cancer_data.target_names
cancer_data.data.shape
cancer_df= pd.DataFrame(cancer_data.data, columns=cancer_data["feature_names"])
cancer_df=cancer_df.assign(target=cancer_data.target)
cancer_df.head()

#SVC, MLP and RFC application on reduced data
clf7= svm.SVC()
clf7.fit(X_train,Y_train)
my_prediction7 = clf7.predict(X_test)
accuracy_test7 = accuracy_score(my_prediction7,Y_test)
print(accuracy_test7)
clf8 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf8.fit(X_train,Y_train)
my_prediction8 = clf8.predict(X_test)
accuracy_test8 = accuracy_score(my_prediction8,Y_test)
print(accuracy_test8)
clf9 = RandomForestClassifier(n_estimators=22)
clf9.fit(X_train,Y_train)
my_prediction9 = clf9.predict(X_test)
accuracy_test9 = accuracy_score(my_prediction9,Y_test)
print(accuracy_test9)

#pre-PCA and postPCA bar graph
plt.bar(['pre-SVC', 'post-SVC'],[accuracy_test1, accuracy_test7] )
plt.bar(['pre-MLP', 'post-MLP'], [accuracy_test2, accuracy_test8])
plt.bar(['pre-RF', 'post-RF'], [accuracy_test3, accuracy_test8])
plt.title('Comparing pre-PCA and post-PCA')
plt.show()